server:
  port: 8889
spring:
  application:
    name: toy-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
    eureka:
      client:
        registerWithEureka: false
        fetchRegistry: false
