server:
  port: 8100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
spring:
  application:
    name: toy-order
  h2:
    console:
      enabled: true  
      path: /order
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/Develop/Github/SpringBlogExam/order;AUTO_SERVER=TRUE
    username: test
    password: 1234
