server:
  port: 8000
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8889/eureka/
spring:
  application:
    name: toy-gateway
	cloud:
		gateway:
		  routes:
		  - id: toy-order
			uri: localhost:8100
			predicates:
			- Path=/orders
			filters:
			- name: Hystrix
				args:
				  name: hystrix
				  fallbackUri: forward:/fallback/first
