server:
  port: 8000
spring:
  application:
    name: toy-gateway
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8889/eureka/
  cloud:
    gateway:
      routes:
      - id: toy-order
        uri: localhost:8100
        predicates: 
        - Path=/orders
