server:
  port: 8102
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
spring:
  application:
    name: toy-payment
  h2:
    console:
      enabled: true  
      path: /payment
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/payment;AUTO_SERVER=TRUE
    username: test
    password: 1234
